auxiliary samplers:
  combined flux index:
    observed: false
    secondary:
    - spectral_index
    selection:
      CombinedFluxIndexSelection:
        boundary: -37.5
        strength: 5
    slope: 3
    type: CombinedFluxIndexSampler
  flare_durations:
    alpha: -1.5
    observed: false
    secondary:
    - flare_times
    selection:
      UnitySelection: {}
    type: FlareDurationAuxSampler
  flare_rate:
    alpha: -1.95
    observed: false
    secondary:
    - variability
    selection:
      UnitySelection: {}
    type: FlareRateAuxSampler
    xmax: 10
    xmin: 0.1
  flare_times:
    obs_time: 7.4
    observed: false
    secondary:
    - flare_rate
    selection:
      UnitySelection: {}
    type: FlareTimeAuxSampler
  flare_amplitudes:
    index: 4.5
    xmin: 1.2
    observed: false
    secondary:
    - flare_times
    selection:
      UnitySelection: {}
    type: FlareAmplitudeAuxSampler
  spectral_index:
    mu: 2.1
    observed: true
    secondary: []
    selection:
      UnitySelection: {}
    sigma: 0.1
    tau: 0.25
    type: SpectralIndexAuxSampler
  variability:
    observed: false
    secondary: []
    selection:
      UnitySelection: {}
    type: VariabilityAuxSampler
    weight: 0.07
luminosity distribution:
  BPLDistribution:
    Lbreak: 1.0e+47
    Lmax: 1.0e+52
    Lmin: 7.0e+43
    alpha: -1.5
    beta: -2.5
seed: 42
spatial distribution:
  ZPowerCosmoDistribution:
    Lambda: 4000
    delta: -4
    r_max: 6
  is_rate: false
