auxiliary samplers:
  combined flux index:
    observed: false
    secondary:
    - spectral_index
    selection:
      CombinedFluxIndexSelection:
        boundary: -37.5
        strength: 5
    slope: 3
    type: CombinedFluxIndexSampler
  flare_durations:
    alpha: -2.0
    observed: false
    secondary:
    - flare_times
    selection:
      UnitySelection: {}
    type: FlareDurationAuxSampler
  flare_rate:
    alpha: -2.1
    observed: false
    secondary:
    - variability
    selection:
      UnitySelection: {}
    type: FlareRateAuxSampler
    xmax: 10
    xmin: 0.1
  flare_times:
    obs_time: 10.0
    observed: false
    secondary:
    - flare_rate
    selection:
      UnitySelection: {}
    type: FlareTimeAuxSampler
  flare_amplitudes:
    alpha: 4.0
    xmin: 1.3
    observed: false
    secondary:
    - flare_times
    selection:
      UnitySelection: {}
    type: FlareAmplitudeAuxSampler
  spectral_index:
    mu: 2.5
    observed: true
    secondary: []
    selection:
      UnitySelection: {}
    sigma: 0.1
    tau: 0.2
    type: SpectralIndexAuxSampler
  variability:
    observed: false
    secondary: []
    selection:
      UnitySelection: {}
    type: VariabilityAuxSampler
    weight: 0.32
luminosity distribution:
  BPLDistribution:
    Lbreak: 1.1e+48
    Lmax: 1.0e+52
    Lmin: 7.0e+43
    alpha: -0.9
    beta: -2.3
seed: 42
spatial distribution:
  SFRDistribution:
    a: 1
    decay: 4.4
    peak: 0.8
    r0: 29
    r_max: 6
    rise: 15.5
  is_rate: false
