auxiliary samplers:
  flare_durations:
    index: 2.0
    observed: false
    secondary:
    - flare_times
    selection:
      UnitySelection: {}
    type: FlareDurationAuxSampler
  flare_rate:
    index: 2.0
    observed: false
    secondary:
    - variability
    selection:
      UnitySelection: {}
    type: FlareRateAuxSampler
    xmax: 10
    xmin: 0.1
  flare_times:
    obs_time: 7.5
    observed: false
    secondary:
    - flare_rate
    selection:
      UnitySelection: {}
    type: FlareTimeAuxSampler
  flare_amplitudes:
    index: 3
    xmin: 1.2
    observed: false
    secondary:
    - flare_times
    selection:
      UnitySelection: {}
    type: FlareAmplitudeAuxSampler
  spectral_index:
    mu: 2.5
    observed: true
    secondary: []
    selection:
      UnitySelection: {}
    sigma: 0.1
    tau: 0.2
    type: SpectralIndexAuxSampler
  variability:
    observed: false
    secondary: []
    selection:
      UnitySelection: {}
    type: VariabilityAuxSampler
    weight: 0.4
flux selection:
  SoftFluxSelection:
    boundary: 4.0e-12
    strength: 2
luminosity distribution:
  BPLDistribution:
    Lbreak: 1.0e+48
    Lmax: 1.0e+52
    Lmin: 7.0e+43
    alpha: -1.1
    beta: -2.5
seed: 160
spatial distribution:
  SFRDistribution:
    a: 1
    decay: 4.7
    peak: 0.6
    r0: 55
    r_max: 6
    rise: 11
  is_rate: false
