auxiliary samplers:
  combined flux index:
    observed: false
    secondary:
    - spectral_index
    selection:
      CombinedFluxIndexSelection:
        boundary: -37.5
        strength: 5
    slope: 3
    type: CombinedFluxIndexSampler
  flare_durations:
    alpha: -2.0
    observed: false
    secondary:
    - flare_times
    selection:
      UnitySelection: {}
    type: FlareDurationAuxSampler
  flare_rate:
    alpha: -2.0
    observed: false
    secondary:
    - variability
    selection:
      UnitySelection: {}
    type: FlareRateAuxSampler
    xmax: 10
    xmin: 0.1
  flare_times:
    obs_time: 7.4
    observed: false
    secondary:
    - flare_rate
    selection:
      UnitySelection: {}
    type: FlareTimeAuxSampler
  spectral_index:
    mu: 2.5
    observed: true
    secondary: []
    selection:
      UnitySelection: {}
    sigma: 0.1
    tau: 0.2
    type: SpectralIndexAuxSampler
  variability:
    observed: false
    secondary: []
    selection:
      UnitySelection: {}
    type: VariabilityAuxSampler
    weight: 0.4
luminosity distribution:
  BPLDistribution:
    Lbreak: 1.0e+48
    Lmax: 1.0e+52
    Lmin: 7.0e+43
    alpha: -1.1
    beta: -2.5
seed: 42
spatial distribution:
  SFRDistribution:
    a: 1
    decay: 4.5
    peak: 0.7
    r0: 27
    r_max: 6
    rise: 15
  is_rate: false
spatial selection:
  GalacticPlaneSelection:
    b_limit: 10
