connection:
  flux_factor: 0.01
  lower_energy: 10000.0
  lower_energy_sim: 50000.0
  upper_energy: 100000000.0
  normalisation_energy: 100000.0
detector:
  Emin_det: 250000.0
  max_cosz: 1
  obs_time: 10.0