auxiliary samplers:
  combined flux index:
    observed: false
    secondary:
    - spectral_index
    selection:
      CombinedFluxIndexSelection:
        boundary: -37.5
        strength: 5
    slope: 3
    type: CombinedFluxIndexSampler
  spectral_index:
    mu: 2.1
    observed: true
    secondary: []
    selection:
      UnitySelection: {}
    sigma: 0.1
    tau: 0.25
    type: SpectralIndexAuxSampler
luminosity distribution:
  BPLDistribution:
    Lbreak: 1.0e+47
    Lmax: 1.0e+52
    Lmin: 7.0e+43
    alpha: -1.5
    beta: -2.5
seed: 42
spatial distribution:
  ZPowerCosmoDistribution:
    Lambda: 3160
    delta: -4
    r_max: 6
  is_rate: false
