auxiliary samplers:
  combined flux index:
    observed: false
    secondary:
    - flux
    - spectral_index
    selection:
      CombinedFluxIndexSelection:
        boundary: -37.5
    slope: 3
    type: CombinedFluxIndexSampler
  flare_amplitudes:
    alpha: 4.5
    observed: false
    secondary:
    - flare_times
    selection:
      UnitySelection: {}
    type: FlareAmplitudeAuxSampler
    xmin: 1.2
  flare_durations:
    alpha: -2.2
    observed: false
    secondary:
    - flare_times
    selection:
      UnitySelection: {}
    type: FlareDurationAuxSampler
  flare_rate:
    alpha: -2.2
    observed: false
    secondary:
    - variability
    selection:
      UnitySelection: {}
    type: FlareRateAuxSampler
    xmax: 10
    xmin: 0.1
  flare_times:
    obs_time: 10.0
    observed: false
    secondary:
    - flare_rate
    selection:
      UnitySelection: {}
    type: FlareTimeAuxSampler
  flux:
    observed: true
    secondary: []
    selection:
      UnitySelection: {}
    sigma: 0.1
    type: FluxSampler
  spectral_index:
    mu: 2.1
    observed: true
    secondary: []
    selection:
      UnitySelection: {}
    sigma: 0.1
    tau: 0.25
    type: SpectralIndexAuxSampler
  variability:
    observed: false
    secondary: []
    selection:
      UnitySelection: {}
    type: VariabilityAuxSampler
    weight: 0.075
flux selection:
  HardFluxSelection:
    boundary: 1.0e-14
luminosity distribution:
  BPLDistribution:
    Lbreak: 1.1e+47
    Lmax: 1.0e+50
    Lmin: 7.0e+43
    alpha: -1.4
    beta: -2.4
seed: 42
spatial distribution:
  ZPowerCosmoDistribution:
    Lambda: 5200
    delta: -3.8
    r_max: 6
  is_rate: false
